/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`v1_account_api_keys_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1AccountApiKeysGetError {
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`v1_account_api_keys_key_code_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1AccountApiKeysKeyCodeDeleteError {
    Status401(models::AuthErrorResponse),
    Status409(models::V1AccountApiKeysKeyCodeDelete409Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`v1_account_api_keys_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1AccountApiKeysPostError {
    Status400(models::AuthErrorResponse),
    Status401(models::AuthErrorResponse),
    Status422(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`v1_account_check_endpoint_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1AccountCheckEndpointDeleteError {
    Status401(models::AuthErrorResponse),
    Status409(models::V1AccountApiKeysKeyCodeDelete409Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`v1_account_check_endpoint_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1AccountCheckEndpointGetError {
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`v1_account_check_endpoint_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1AccountCheckEndpointPostError {
    Status400(models::AuthErrorResponse),
    Status401(models::AuthErrorResponse),
    Status422(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`v1_account_config_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1AccountConfigGetError {
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`v1_account_secret_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1AccountSecretPostError {
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`v1_account_secrets_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1AccountSecretsGetError {
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`v1_account_secrets_secret_code_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1AccountSecretsSecretCodeDeleteError {
    Status401(models::AuthErrorResponse),
    Status409(models::V1AccountApiKeysKeyCodeDelete409Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`v1_account_usage_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1AccountUsageGetError {
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}


pub async fn v1_account_api_keys_get(configuration: &configuration::Configuration, ) -> Result<models::AuthListApiKeysResponse, Error<V1AccountApiKeysGetError>> {

    let uri_str = format!("{}/v1/account/api-keys", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AuthListApiKeysResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AuthListApiKeysResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<V1AccountApiKeysGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn v1_account_api_keys_key_code_delete(configuration: &configuration::Configuration, key_code: &str) -> Result<(), Error<V1AccountApiKeysKeyCodeDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_key_code = key_code;

    let uri_str = format!("{}/v1/account/api-keys/{key_code}", configuration.base_path, key_code=crate::apis::urlencode(p_path_key_code));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<V1AccountApiKeysKeyCodeDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn v1_account_api_keys_post(configuration: &configuration::Configuration, auth_create_api_key_request: models::AuthCreateApiKeyRequest) -> Result<models::AuthCreateApiKeyResponse, Error<V1AccountApiKeysPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_auth_create_api_key_request = auth_create_api_key_request;

    let uri_str = format!("{}/v1/account/api-keys", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_auth_create_api_key_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AuthCreateApiKeyResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AuthCreateApiKeyResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<V1AccountApiKeysPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn v1_account_check_endpoint_delete(configuration: &configuration::Configuration, ) -> Result<(), Error<V1AccountCheckEndpointDeleteError>> {

    let uri_str = format!("{}/v1/account/check-endpoint", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<V1AccountCheckEndpointDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns the URL, method and bearer token preview for the check endpoint used by flow quoting. The full bearer token is never returned.
pub async fn v1_account_check_endpoint_get(configuration: &configuration::Configuration, ) -> Result<models::AuthCheckEndpointResponse, Error<V1AccountCheckEndpointGetError>> {

    let uri_str = format!("{}/v1/account/check-endpoint", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AuthCheckEndpointResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AuthCheckEndpointResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<V1AccountCheckEndpointGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Stores or updates the URL, method and bearer token used to quote flows against the client's own service. A single configuration exists per client.
pub async fn v1_account_check_endpoint_post(configuration: &configuration::Configuration, auth_set_check_endpoint_request: models::AuthSetCheckEndpointRequest) -> Result<models::AuthCheckEndpointResponse, Error<V1AccountCheckEndpointPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_auth_set_check_endpoint_request = auth_set_check_endpoint_request;

    let uri_str = format!("{}/v1/account/check-endpoint", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_auth_set_check_endpoint_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AuthCheckEndpointResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AuthCheckEndpointResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<V1AccountCheckEndpointPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn v1_account_config_get(configuration: &configuration::Configuration, ) -> Result<(), Error<V1AccountConfigGetError>> {

    let uri_str = format!("{}/v1/account/config", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<V1AccountConfigGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn v1_account_secret_post(configuration: &configuration::Configuration, ) -> Result<models::AuthCreateSecretResponse, Error<V1AccountSecretPostError>> {

    let uri_str = format!("{}/v1/account/secret", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AuthCreateSecretResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AuthCreateSecretResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<V1AccountSecretPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn v1_account_secrets_get(configuration: &configuration::Configuration, ) -> Result<models::AuthListSecretsResponse, Error<V1AccountSecretsGetError>> {

    let uri_str = format!("{}/v1/account/secrets", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AuthListSecretsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AuthListSecretsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<V1AccountSecretsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn v1_account_secrets_secret_code_delete(configuration: &configuration::Configuration, secret_code: &str) -> Result<(), Error<V1AccountSecretsSecretCodeDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_secret_code = secret_code;

    let uri_str = format!("{}/v1/account/secrets/{secret_code}", configuration.base_path, secret_code=crate::apis::urlencode(p_path_secret_code));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<V1AccountSecretsSecretCodeDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn v1_account_usage_get(configuration: &configuration::Configuration, start_date: Option<chrono::DateTime<chrono::FixedOffset>>, end_date: Option<chrono::DateTime<chrono::FixedOffset>>) -> Result<(), Error<V1AccountUsageGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_start_date = start_date;
    let p_query_end_date = end_date;

    let uri_str = format!("{}/v1/account/usage", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_start_date {
        req_builder = req_builder.query(&[("start_date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_end_date {
        req_builder = req_builder.query(&[("end_date", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<V1AccountUsageGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

