/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`v1_historical_events_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1HistoricalEventsGetError {
    Status401(models::TrendsErrorResponse),
    Status403(models::TrendsErrorResponse),
    Status422(models::TrendsErrorResponse),
    Status500(models::TrendsErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`v1_historical_odds_event_id_ext_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1HistoricalOddsEventIdExtGetError {
    Status400(models::TrendsErrorResponse),
    Status401(models::TrendsErrorResponse),
    Status403(models::TrendsErrorResponse),
    Status404(models::TrendsErrorResponse),
    Status422(models::TrendsErrorResponse),
    Status500(models::TrendsErrorResponse),
    Status502(models::TrendsErrorResponse),
    UnknownValue(serde_json::Value),
}


/// Returns a paginated catalog of per-event historical odds files the authenticated client has access to. Each result entry carries pre-baked download URLs for the JSON and CSV payloads; clients GET those URLs directly. Results are scoped to the authenticated client; callers without a client association receive `403 Forbidden`. 
pub async fn v1_historical_events_get(configuration: &configuration::Configuration, schema_version: Option<&str>, sport_id: Option<i64>, league_id: Option<i64>, team_id: Option<i64>, start_date: Option<&str>, end_date: Option<&str>, page: Option<i64>, page_size: Option<i64>) -> Result<serde_json::Value, Error<V1HistoricalEventsGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_schema_version = schema_version;
    let p_query_sport_id = sport_id;
    let p_query_league_id = league_id;
    let p_query_team_id = team_id;
    let p_query_start_date = start_date;
    let p_query_end_date = end_date;
    let p_query_page = page;
    let p_query_page_size = page_size;

    let uri_str = format!("{}/v1/historical/events", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_schema_version {
        req_builder = req_builder.query(&[("schema_version", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sport_id {
        req_builder = req_builder.query(&[("sport_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_league_id {
        req_builder = req_builder.query(&[("league_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team_id {
        req_builder = req_builder.query(&[("team_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_start_date {
        req_builder = req_builder.query(&[("start_date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_end_date {
        req_builder = req_builder.query(&[("end_date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("page_size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `serde_json::Value`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<V1HistoricalEventsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Resolves the requested per-event file for the authenticated client and streams the JSON or CSV payload back. The response body is the raw file content (not the manifest envelope); the API takes care of fetching the bytes from the underlying CDN so callers see a single HTTP call per file.  The `sha256` of the bytes-at-rest is exposed as a strong `ETag`. Clients can short-circuit with `If-None-Match` to receive `304 Not Modified`. `Range` requests are forwarded upstream and `206 Partial Content` responses are relayed unchanged — useful for resuming multi-MB CSV downloads. 
pub async fn v1_historical_odds_event_id_ext_get(configuration: &configuration::Configuration, event_id: i64, ext: &str, schema_version: Option<&str>) -> Result<serde_json::Value, Error<V1HistoricalOddsEventIdExtGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_event_id = event_id;
    let p_path_ext = ext;
    let p_query_schema_version = schema_version;

    let uri_str = format!("{}/v1/historical/odds/{event_id}.{ext}", configuration.base_path, event_id=p_path_event_id, ext=crate::apis::urlencode(p_path_ext));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_schema_version {
        req_builder = req_builder.query(&[("schema_version", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `serde_json::Value`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<V1HistoricalOddsEventIdExtGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

