/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`v1_affiliates_links_clicks_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1AffiliatesLinksClicksGetError {
    Status403(models::AffiliateErrorResponse),
    Status422(models::AffiliateErrorResponse),
    Status500(models::AffiliateErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`v1_affiliates_links_inventory_summary_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1AffiliatesLinksInventorySummaryGetError {
    Status403(models::AffiliateErrorResponse),
    Status422(models::AffiliateErrorResponse),
    Status500(models::AffiliateErrorResponse),
    UnknownValue(serde_json::Value),
}


/// Per-link, per-day impression and click counts for the authenticated client.
pub async fn v1_affiliates_links_clicks_get(configuration: &configuration::Configuration, start_date: chrono::NaiveDate, end_date: chrono::NaiveDate, operator_id: Option<i64>, country_code: Option<&str>, subnational_region_code: Option<&str>, offer_campaign: Option<&str>, offer_label: Option<&str>) -> Result<serde_json::Value, Error<V1AffiliatesLinksClicksGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_start_date = start_date;
    let p_query_end_date = end_date;
    let p_query_operator_id = operator_id;
    let p_query_country_code = country_code;
    let p_query_subnational_region_code = subnational_region_code;
    let p_query_offer_campaign = offer_campaign;
    let p_query_offer_label = offer_label;

    let uri_str = format!("{}/v1/affiliates/links/clicks", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("start_date", &p_query_start_date.to_string())]);
    req_builder = req_builder.query(&[("end_date", &p_query_end_date.to_string())]);
    if let Some(ref param_value) = p_query_operator_id {
        req_builder = req_builder.query(&[("operator_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_country_code {
        req_builder = req_builder.query(&[("country_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_subnational_region_code {
        req_builder = req_builder.query(&[("subnational_region_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offer_campaign {
        req_builder = req_builder.query(&[("offer_campaign", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offer_label {
        req_builder = req_builder.query(&[("offer_label", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `serde_json::Value`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<V1AffiliatesLinksClicksGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Active/inactive link counts grouped by the requested dimension.
pub async fn v1_affiliates_links_inventory_summary_get(configuration: &configuration::Configuration, group_by: Option<&str>) -> Result<serde_json::Value, Error<V1AffiliatesLinksInventorySummaryGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_group_by = group_by;

    let uri_str = format!("{}/v1/affiliates/links/inventory-summary", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_group_by {
        req_builder = req_builder.query(&[("group_by", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `serde_json::Value`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<V1AffiliatesLinksInventorySummaryGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

