/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1AffiliatesLinksPostRequest {
    #[serde(rename = "android_deep_link_url", skip_serializing_if = "Option::is_none")]
    pub android_deep_link_url: Option<String>,
    #[serde(rename = "country_code", skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
    #[serde(rename = "ios_deep_link_url", skip_serializing_if = "Option::is_none")]
    pub ios_deep_link_url: Option<String>,
    #[serde(rename = "is_active", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(rename = "offer_call_to_action", skip_serializing_if = "Option::is_none")]
    pub offer_call_to_action: Option<String>,
    #[serde(rename = "offer_campaign", skip_serializing_if = "Option::is_none")]
    pub offer_campaign: Option<String>,
    #[serde(rename = "offer_category_id")]
    pub offer_category_id: i64,
    #[serde(rename = "offer_display_bullets", skip_serializing_if = "Option::is_none")]
    pub offer_display_bullets: Option<Vec<String>>,
    #[serde(rename = "offer_display_small_print", skip_serializing_if = "Option::is_none")]
    pub offer_display_small_print: Option<String>,
    #[serde(rename = "offer_ev_usd", skip_serializing_if = "Option::is_none")]
    pub offer_ev_usd: Option<f64>,
    #[serde(rename = "offer_label", skip_serializing_if = "Option::is_none")]
    pub offer_label: Option<String>,
    #[serde(rename = "offer_priority", skip_serializing_if = "Option::is_none")]
    pub offer_priority: Option<i32>,
    #[serde(rename = "offer_tagline", skip_serializing_if = "Option::is_none")]
    pub offer_tagline: Option<String>,
    /// One of operator_id or operator_name is required.
    #[serde(rename = "operator_id", skip_serializing_if = "Option::is_none")]
    pub operator_id: Option<i64>,
    #[serde(rename = "operator_name", skip_serializing_if = "Option::is_none")]
    pub operator_name: Option<String>,
    #[serde(rename = "source_network_affiliate_partner_id", skip_serializing_if = "Option::is_none")]
    pub source_network_affiliate_partner_id: Option<i64>,
    /// Omit for country-grain inventory.
    #[serde(rename = "subnational_region_code", skip_serializing_if = "Option::is_none")]
    pub subnational_region_code: Option<String>,
    #[serde(rename = "web_deep_link_url")]
    pub web_deep_link_url: String,
}

impl V1AffiliatesLinksPostRequest {
    pub fn new(offer_category_id: i64, web_deep_link_url: String) -> V1AffiliatesLinksPostRequest {
        V1AffiliatesLinksPostRequest {
            android_deep_link_url: None,
            country_code: None,
            ios_deep_link_url: None,
            is_active: None,
            offer_call_to_action: None,
            offer_campaign: None,
            offer_category_id,
            offer_display_bullets: None,
            offer_display_small_print: None,
            offer_ev_usd: None,
            offer_label: None,
            offer_priority: None,
            offer_tagline: None,
            operator_id: None,
            operator_name: None,
            source_network_affiliate_partner_id: None,
            subnational_region_code: None,
            web_deep_link_url,
        }
    }
}

