/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1AffiliatesLinksBulkDeactivatePostRequest {
    #[serde(rename = "filter")]
    pub filter: serde_json::Value,
}

impl V1AffiliatesLinksBulkDeactivatePostRequest {
    pub fn new(filter: serde_json::Value) -> V1AffiliatesLinksBulkDeactivatePostRequest {
        V1AffiliatesLinksBulkDeactivatePostRequest {
            filter,
        }
    }
}

