/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1AffiliatesLinksBulkPatchRequest {
    #[serde(rename = "filter")]
    pub filter: serde_json::Value,
    #[serde(rename = "patch")]
    pub patch: serde_json::Value,
}

impl V1AffiliatesLinksBulkPatchRequest {
    pub fn new(filter: serde_json::Value, patch: serde_json::Value) -> V1AffiliatesLinksBulkPatchRequest {
        V1AffiliatesLinksBulkPatchRequest {
            filter,
            patch,
        }
    }
}

