/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1OddsUpcomingOddsByEventPostRequest {
    /// The event ID to retrieve odds for
    #[serde(rename = "event_id")]
    pub event_id: i64,
    /// Optional list of operator IDs to filter by
    #[serde(rename = "operator_ids", skip_serializing_if = "Option::is_none")]
    pub operator_ids: Option<Vec<i32>>,
    /// Page number for pagination
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    /// Number of results per page
    #[serde(rename = "page_size", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i64>,
}

impl V1OddsUpcomingOddsByEventPostRequest {
    pub fn new(event_id: i64) -> V1OddsUpcomingOddsByEventPostRequest {
        V1OddsUpcomingOddsByEventPostRequest {
            event_id,
            operator_ids: None,
            page: None,
            page_size: None,
        }
    }
}

