/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1EventsUpcomingEventsPostRequest {
    /// Filter by event date (YYYY-MM-DD). Defaults to today (UTC).
    #[serde(rename = "event_date", skip_serializing_if = "Option::is_none")]
    pub event_date: Option<chrono::NaiveDate>,
    #[serde(rename = "league_id", skip_serializing_if = "Option::is_none")]
    pub league_id: Option<i64>,
    /// League external key (e.g. 'nba', 'united-states.nba'). Alternative to league_id. If both are provided, league_id takes precedence.
    #[serde(rename = "league_key", skip_serializing_if = "Option::is_none")]
    pub league_key: Option<String>,
    /// Page number for pagination
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    /// Number of events per page
    #[serde(rename = "page_size", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i64>,
    #[serde(rename = "sport_id", skip_serializing_if = "Option::is_none")]
    pub sport_id: Option<i64>,
    /// Sport external key (e.g. 'american-football'). Alternative to sport_id. If both are provided, sport_id takes precedence.
    #[serde(rename = "sport_key", skip_serializing_if = "Option::is_none")]
    pub sport_key: Option<String>,
    /// IANA timezone for date interpretation (e.g. 'UTC', 'America/New_York', 'Europe/London')
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
}

impl V1EventsUpcomingEventsPostRequest {
    pub fn new() -> V1EventsUpcomingEventsPostRequest {
        V1EventsUpcomingEventsPostRequest {
            event_date: None,
            league_id: None,
            league_key: None,
            page: None,
            page_size: None,
            sport_id: None,
            sport_key: None,
            timezone: None,
        }
    }
}

