/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1AffiliatesLinksBulkPost202Response {
    #[serde(rename = "job_id", skip_serializing_if = "Option::is_none")]
    pub job_id: Option<uuid::Uuid>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    #[serde(rename = "poll_url", skip_serializing_if = "Option::is_none")]
    pub poll_url: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "submitted_rows", skip_serializing_if = "Option::is_none")]
    pub submitted_rows: Option<i32>,
}

impl V1AffiliatesLinksBulkPost202Response {
    pub fn new() -> V1AffiliatesLinksBulkPost202Response {
        V1AffiliatesLinksBulkPost202Response {
            job_id: None,
            mode: None,
            poll_url: None,
            status: None,
            submitted_rows: None,
        }
    }
}

