/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ReferencesTagTypesTagTypeIdChildrenGet200Response {
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<serde_json::Value>,
    #[serde(rename = "records", skip_serializing_if = "Option::is_none")]
    pub records: Option<Vec<serde_json::Value>>,
}

impl V1ReferencesTagTypesTagTypeIdChildrenGet200Response {
    pub fn new() -> V1ReferencesTagTypesTagTypeIdChildrenGet200Response {
        V1ReferencesTagTypesTagTypeIdChildrenGet200Response {
            parent: None,
            records: None,
        }
    }
}

