/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1TrendsFlowsPostRequest {
    /// Filter by bet type. If omitted, returns mixed singles and parlays.
    #[serde(rename = "bet_type", skip_serializing_if = "Option::is_none")]
    pub bet_type: Option<BetType>,
    /// Deprecated — use `betting_market_category_ids` instead (e.g. Shooting Props, Game Props etc.). A bare `betting_market_category_id` is treated as `betting_market_category_ids: [betting_market_category_id]`.
    #[serde(rename = "betting_market_category_id", skip_serializing_if = "Option::is_none")]
    pub betting_market_category_id: Option<i64>,
    /// Filter by one or more betting market category IDs (e.g. Shooting Props, Game Props etc.). Empty array = no filter.
    #[serde(rename = "betting_market_category_ids", skip_serializing_if = "Option::is_none")]
    pub betting_market_category_ids: Option<Vec<i64>>,
    /// Filter by betting market entity type
    #[serde(rename = "betting_market_entity_type", skip_serializing_if = "Option::is_none")]
    pub betting_market_entity_type: Option<BettingMarketEntityType>,
    /// Filter by betting market IDs
    #[serde(rename = "betting_market_ids", skip_serializing_if = "Option::is_none")]
    pub betting_market_ids: Option<Vec<i64>>,
    /// Deprecated — use `betting_market_position_ids` instead. A bare `betting_market_position_id` is treated as `betting_market_position_ids: [betting_market_position_id]`.
    #[serde(rename = "betting_market_position_id", skip_serializing_if = "Option::is_none")]
    pub betting_market_position_id: Option<i64>,
    /// Filter by one or more betting market position IDs. Empty array = no filter.
    #[serde(rename = "betting_market_position_ids", skip_serializing_if = "Option::is_none")]
    pub betting_market_position_ids: Option<Vec<i64>>,
    /// Deprecated — use `event_ids` instead. A bare `event_id` is treated as `event_ids: [event_id]`.
    #[serde(rename = "event_id", skip_serializing_if = "Option::is_none")]
    pub event_id: Option<i64>,
    /// Filter by one or more event IDs. Empty array = no filter.
    #[serde(rename = "event_ids", skip_serializing_if = "Option::is_none")]
    pub event_ids: Option<Vec<i64>>,
    /// Filter events starting on or after this value. Accepts a date ('2026-04-19') or full ISO 8601 timestamp ('2026-04-19T00:00:00Z').
    #[serde(rename = "event_start_date_from", skip_serializing_if = "Option::is_none")]
    pub event_start_date_from: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Filter events starting on or before this value. Accepts a date ('2026-04-26') or full ISO 8601 timestamp ('2026-04-26T23:59:59Z').
    #[serde(rename = "event_start_date_to", skip_serializing_if = "Option::is_none")]
    pub event_start_date_to: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Sub-type for fact flows. Defaults to 'base' if omitted.
    #[serde(rename = "fact_flow_type", skip_serializing_if = "Option::is_none")]
    pub fact_flow_type: Option<FactFlowType>,
    /// Type of flow to return. 'plain' only returns parlays.
    #[serde(rename = "flow_type", skip_serializing_if = "Option::is_none")]
    pub flow_type: Option<FlowType>,
    /// Filter by focus entity type ID
    #[serde(rename = "focus_entity_type_id", skip_serializing_if = "Option::is_none")]
    pub focus_entity_type_id: Option<i64>,
    /// When true, include full hit rate data in response
    #[serde(rename = "full_hit_rate", skip_serializing_if = "Option::is_none")]
    pub full_hit_rate: Option<bool>,
    /// When false, exclude alt lines. Defaults to true.
    #[serde(rename = "include_alt_lines", skip_serializing_if = "Option::is_none")]
    pub include_alt_lines: Option<bool>,
    /// When true, returns operator-specific odds and deeplink URLs (bet_ios_deep_link_url, bet_android_deep_link_url, bet_web_deep_link_url) for each flow. Requires exactly one operator_id in operator_ids.
    #[serde(rename = "include_deeplinks", skip_serializing_if = "Option::is_none")]
    pub include_deeplinks: Option<bool>,
    /// When true, return only basic trends (omit fact flows with conditions)
    #[serde(rename = "include_only_basic_trends", skip_serializing_if = "Option::is_none")]
    pub include_only_basic_trends: Option<bool>,
    /// When true, include star sign/horoscope content in flows
    #[serde(rename = "include_star_sign_content", skip_serializing_if = "Option::is_none")]
    pub include_star_sign_content: Option<bool>,
    /// Deprecated — use `league_ids` instead. A bare `league_id` is treated as `league_ids: [league_id]`.
    #[serde(rename = "league_id", skip_serializing_if = "Option::is_none")]
    pub league_id: Option<i64>,
    /// Filter by one or more league IDs. Empty array = no filter.
    #[serde(rename = "league_ids", skip_serializing_if = "Option::is_none")]
    pub league_ids: Option<Vec<i64>>,
    /// League external key (e.g. 'nba', 'united-states.nba'). Format: {league_key} or {country_key}.{league_key}. Alternative to league_id. If both are provided, league_id takes precedence.
    #[serde(rename = "league_key", skip_serializing_if = "Option::is_none")]
    pub league_key: Option<String>,
    /// Filter by likelihood category
    #[serde(rename = "likelihood_type", skip_serializing_if = "Option::is_none")]
    pub likelihood_type: Option<LikelihoodType>,
    /// Maximum hit rate threshold filter (0-100)
    #[serde(rename = "max_hit_rate_threshold", skip_serializing_if = "Option::is_none")]
    pub max_hit_rate_threshold: Option<i32>,
    /// Maximum implied probability threshold filter
    #[serde(rename = "max_implied_probability_threshold", skip_serializing_if = "Option::is_none")]
    pub max_implied_probability_threshold: Option<f64>,
    /// Minimum hit rate threshold filter (0-100)
    #[serde(rename = "min_hit_rate_threshold", skip_serializing_if = "Option::is_none")]
    pub min_hit_rate_threshold: Option<i32>,
    /// Minimum implied probability threshold filter
    #[serde(rename = "min_implied_probability_threshold", skip_serializing_if = "Option::is_none")]
    pub min_implied_probability_threshold: Option<f64>,
    /// Odds display format. Defaults per product_mode (dfs→multiplier, prediction_market→percent, else american).
    #[serde(rename = "odds_format", skip_serializing_if = "Option::is_none")]
    pub odds_format: Option<OddsFormat>,
    /// Filter by operator IDs
    #[serde(rename = "operator_ids", skip_serializing_if = "Option::is_none")]
    pub operator_ids: Option<Vec<i64>>,
    /// Filter by operator external keys (e.g. 'draftkings'). Format: {operator_key}. Resolved IDs are merged with operator_ids.
    #[serde(rename = "operator_keys", skip_serializing_if = "Option::is_none")]
    pub operator_keys: Option<Vec<String>>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    #[serde(rename = "page_size", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i64>,
    /// Deprecated — use `player_ids` instead. A bare `player_id` is treated as `player_ids: [player_id]`.
    #[serde(rename = "player_id", skip_serializing_if = "Option::is_none")]
    pub player_id: Option<i64>,
    /// Filter by one or more player IDs. Empty array = no filter.
    #[serde(rename = "player_ids", skip_serializing_if = "Option::is_none")]
    pub player_ids: Option<Vec<i64>>,
    /// Player external key (e.g. 'nikola-vucevic', 'chicago-bulls.tre-jones', 'nba.boston-celtics.nikola-vucevic'). Format: {player_key} or {team_key}.{player_key} or {league_key}.{team_key}.{player_key}. Alternative to player_id. If both are provided, player_id takes precedence.
    #[serde(rename = "player_key", skip_serializing_if = "Option::is_none")]
    pub player_key: Option<String>,
    /// Display mode. dfs rewrites stat lines to MORE/LESS; on the paginated flows endpoints it also auto-filters to over/under player props (entity_type=player, positions [4,5]) unless an entity/position filter is set.
    #[serde(rename = "product_mode", skip_serializing_if = "Option::is_none")]
    pub product_mode: Option<ProductMode>,
    /// Filter by split type (overs or unders)
    #[serde(rename = "split_type", skip_serializing_if = "Option::is_none")]
    pub split_type: Option<SplitType>,
    /// Deprecated — use `sport_ids` instead. A bare `sport_id` is treated as `sport_ids: [sport_id]`.
    #[serde(rename = "sport_id", skip_serializing_if = "Option::is_none")]
    pub sport_id: Option<i64>,
    /// Filter by one or more sport IDs. Empty array = no filter.
    #[serde(rename = "sport_ids", skip_serializing_if = "Option::is_none")]
    pub sport_ids: Option<Vec<i64>>,
    /// Sport external key (e.g. 'american-football'). Format: {sport_key}. Alternative to sport_id. If both are provided, sport_id takes precedence.
    #[serde(rename = "sport_key", skip_serializing_if = "Option::is_none")]
    pub sport_key: Option<String>,
    /// When true, only return flows for events starting soon
    #[serde(rename = "starting_soon", skip_serializing_if = "Option::is_none")]
    pub starting_soon: Option<bool>,
    /// Deprecated — use `team_ids` instead. A bare `team_id` is treated as `team_ids: [team_id]`.
    #[serde(rename = "team_id", skip_serializing_if = "Option::is_none")]
    pub team_id: Option<i64>,
    /// Filter by one or more team IDs. Empty array = no filter.
    #[serde(rename = "team_ids", skip_serializing_if = "Option::is_none")]
    pub team_ids: Option<Vec<i64>>,
    /// Team external key (e.g. 'new-england-patriots', 'nfl.new-england-patriots'). Format: {team_key} or {league_key}.{team_key}. Alternative to team_id. If both are provided, team_id takes precedence.
    #[serde(rename = "team_key", skip_serializing_if = "Option::is_none")]
    pub team_key: Option<String>,
    /// Team split filter value
    #[serde(rename = "team_split", skip_serializing_if = "Option::is_none")]
    pub team_split: Option<String>,
    /// When true, the logo fields on each flow, leg, and multi-trend slot (default_logo_url, logo_url_1, logo_url_2) are replaced with cartoon-jersey image URLs derived from the relevant team, player, or league. When false or omitted, the original logo URLs are returned. Defaults to false.
    #[serde(rename = "use_cartoon_images", skip_serializing_if = "Option::is_none")]
    pub use_cartoon_images: Option<bool>,
}

impl V1TrendsFlowsPostRequest {
    pub fn new() -> V1TrendsFlowsPostRequest {
        V1TrendsFlowsPostRequest {
            bet_type: None,
            betting_market_category_id: None,
            betting_market_category_ids: None,
            betting_market_entity_type: None,
            betting_market_ids: None,
            betting_market_position_id: None,
            betting_market_position_ids: None,
            event_id: None,
            event_ids: None,
            event_start_date_from: None,
            event_start_date_to: None,
            fact_flow_type: None,
            flow_type: None,
            focus_entity_type_id: None,
            full_hit_rate: None,
            include_alt_lines: None,
            include_deeplinks: None,
            include_only_basic_trends: None,
            include_star_sign_content: None,
            league_id: None,
            league_ids: None,
            league_key: None,
            likelihood_type: None,
            max_hit_rate_threshold: None,
            max_implied_probability_threshold: None,
            min_hit_rate_threshold: None,
            min_implied_probability_threshold: None,
            odds_format: None,
            operator_ids: None,
            operator_keys: None,
            page: None,
            page_size: None,
            player_id: None,
            player_ids: None,
            player_key: None,
            product_mode: None,
            split_type: None,
            sport_id: None,
            sport_ids: None,
            sport_key: None,
            starting_soon: None,
            team_id: None,
            team_ids: None,
            team_key: None,
            team_split: None,
            use_cartoon_images: None,
        }
    }
}
/// Filter by bet type. If omitted, returns mixed singles and parlays.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BetType {
    #[serde(rename = "singles")]
    Singles,
    #[serde(rename = "parlay")]
    Parlay,
    #[serde(rename = "same_game_parlay")]
    SameGameParlay,
}

impl Default for BetType {
    fn default() -> BetType {
        Self::Singles
    }
}
/// Filter by betting market entity type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BettingMarketEntityType {
    #[serde(rename = "player")]
    Player,
    #[serde(rename = "team")]
    Team,
    #[serde(rename = "event")]
    Event,
}

impl Default for BettingMarketEntityType {
    fn default() -> BettingMarketEntityType {
        Self::Player
    }
}
/// Sub-type for fact flows. Defaults to 'base' if omitted.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FactFlowType {
    #[serde(rename = "base")]
    Base,
    #[serde(rename = "expanded")]
    Expanded,
    #[serde(rename = "multi")]
    Multi,
}

impl Default for FactFlowType {
    fn default() -> FactFlowType {
        Self::Base
    }
}
/// Type of flow to return. 'plain' only returns parlays.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FlowType {
    #[serde(rename = "fact")]
    Fact,
    #[serde(rename = "fun")]
    Fun,
    #[serde(rename = "plain")]
    Plain,
}

impl Default for FlowType {
    fn default() -> FlowType {
        Self::Fact
    }
}
/// Filter by likelihood category
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LikelihoodType {
    #[serde(rename = "likely")]
    Likely,
    #[serde(rename = "possible")]
    Possible,
    #[serde(rename = "longshot")]
    Longshot,
}

impl Default for LikelihoodType {
    fn default() -> LikelihoodType {
        Self::Likely
    }
}
/// Odds display format. Defaults per product_mode (dfs→multiplier, prediction_market→percent, else american).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OddsFormat {
    #[serde(rename = "american")]
    American,
    #[serde(rename = "decimal")]
    Decimal,
    #[serde(rename = "fractional")]
    Fractional,
    #[serde(rename = "multiplier")]
    Multiplier,
    #[serde(rename = "percent")]
    Percent,
}

impl Default for OddsFormat {
    fn default() -> OddsFormat {
        Self::American
    }
}
/// Display mode. dfs rewrites stat lines to MORE/LESS; on the paginated flows endpoints it also auto-filters to over/under player props (entity_type=player, positions [4,5]) unless an entity/position filter is set.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProductMode {
    #[serde(rename = "sportsbook")]
    Sportsbook,
    #[serde(rename = "dfs")]
    Dfs,
    #[serde(rename = "prediction_market")]
    PredictionMarket,
}

impl Default for ProductMode {
    fn default() -> ProductMode {
        Self::Sportsbook
    }
}
/// Filter by split type (overs or unders)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SplitType {
    #[serde(rename = "overs")]
    Overs,
    #[serde(rename = "unders")]
    Unders,
}

impl Default for SplitType {
    fn default() -> SplitType {
        Self::Overs
    }
}

