/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1AffiliatesOffersPostRequest {
    #[serde(rename = "country_code", skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
    #[serde(rename = "excluded_operator_ids", skip_serializing_if = "Option::is_none")]
    pub excluded_operator_ids: Option<Vec<i64>>,
    #[serde(rename = "hide_offers_links", skip_serializing_if = "Option::is_none")]
    pub hide_offers_links: Option<bool>,
    #[serde(rename = "offer_campaign", skip_serializing_if = "Option::is_none")]
    pub offer_campaign: Option<String>,
    #[serde(rename = "operator_ids", skip_serializing_if = "Option::is_none")]
    pub operator_ids: Option<Vec<i64>>,
    #[serde(rename = "operator_keys", skip_serializing_if = "Option::is_none")]
    pub operator_keys: Option<Vec<String>>,
    #[serde(rename = "operator_type_ids", skip_serializing_if = "Option::is_none")]
    pub operator_type_ids: Option<Vec<i64>>,
    #[serde(rename = "subnational_region_code", skip_serializing_if = "Option::is_none")]
    pub subnational_region_code: Option<String>,
}

impl V1AffiliatesOffersPostRequest {
    pub fn new() -> V1AffiliatesOffersPostRequest {
        V1AffiliatesOffersPostRequest {
            country_code: None,
            excluded_operator_ids: None,
            hide_offers_links: None,
            offer_campaign: None,
            operator_ids: None,
            operator_keys: None,
            operator_type_ids: None,
            subnational_region_code: None,
        }
    }
}

