/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1AffiliatesDealsPostRequest {
    #[serde(rename = "country_code", skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
    #[serde(rename = "excluded_operator_ids", skip_serializing_if = "Option::is_none")]
    pub excluded_operator_ids: Option<Vec<i64>>,
    #[serde(rename = "hide_offers_links", skip_serializing_if = "Option::is_none")]
    pub hide_offers_links: Option<bool>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Mode>,
    #[serde(rename = "offer_campaign", skip_serializing_if = "Option::is_none")]
    pub offer_campaign: Option<String>,
    #[serde(rename = "offer_type", skip_serializing_if = "Option::is_none")]
    pub offer_type: Option<String>,
    #[serde(rename = "operator_ids", skip_serializing_if = "Option::is_none")]
    pub operator_ids: Option<Vec<i64>>,
    #[serde(rename = "operator_keys", skip_serializing_if = "Option::is_none")]
    pub operator_keys: Option<Vec<String>>,
    #[serde(rename = "operator_type_ids", skip_serializing_if = "Option::is_none")]
    pub operator_type_ids: Option<Vec<i64>>,
    #[serde(rename = "page_number", skip_serializing_if = "Option::is_none")]
    pub page_number: Option<i32>,
    #[serde(rename = "page_size", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
    #[serde(rename = "subnational_region_code", skip_serializing_if = "Option::is_none")]
    pub subnational_region_code: Option<String>,
    /// When true
    #[serde(rename = "with_reviews", skip_serializing_if = "Option::is_none")]
    pub with_reviews: Option<bool>,
}

impl V1AffiliatesDealsPostRequest {
    pub fn new() -> V1AffiliatesDealsPostRequest {
        V1AffiliatesDealsPostRequest {
            country_code: None,
            excluded_operator_ids: None,
            hide_offers_links: None,
            mode: None,
            offer_campaign: None,
            offer_type: None,
            operator_ids: None,
            operator_keys: None,
            operator_type_ids: None,
            page_number: None,
            page_size: None,
            subnational_region_code: None,
            with_reviews: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "carousel")]
    Carousel,
    #[serde(rename = "featured")]
    Featured,
    #[serde(rename = "list")]
    List,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Carousel
    }
}

