/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1AffiliatesParlayPostRequest {
    /// ISO 3166-1 alpha-2 country code.
    #[serde(rename = "country_code", skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
    /// The event betting market positions that make up the parlay legs.
    #[serde(rename = "event_betting_market_position_ids")]
    pub event_betting_market_position_ids: Vec<i64>,
    /// When true, offer metadata is returned without the deep-link URLs.
    #[serde(rename = "hide_offers_links", skip_serializing_if = "Option::is_none")]
    pub hide_offers_links: Option<bool>,
    /// Odds display format. Defaults per product_mode (dfs→multiplier, prediction_market→percent, else american).
    #[serde(rename = "odds_format", skip_serializing_if = "Option::is_none")]
    pub odds_format: Option<OddsFormat>,
    /// Optional campaign filter. Renders only offers tagged with this campaign.
    #[serde(rename = "offer_campaign", skip_serializing_if = "Option::is_none")]
    pub offer_campaign: Option<String>,
    /// Optional list of operator IDs to gate which operators appear in the cart.
    #[serde(rename = "operator_ids", skip_serializing_if = "Option::is_none")]
    pub operator_ids: Option<Vec<i64>>,
    /// Optional operator external keys (e.g. 'draftkings'). Resolved IDs are merged with operator_ids.
    #[serde(rename = "operator_keys", skip_serializing_if = "Option::is_none")]
    pub operator_keys: Option<Vec<String>>,
    /// Display mode. dfs rewrites leg stat lines to MORE/LESS.
    #[serde(rename = "product_mode", skip_serializing_if = "Option::is_none")]
    pub product_mode: Option<ProductMode>,
    /// ISO 3166-2 subnational region code (used for offer/deeplink resolution).
    #[serde(rename = "subnational_region_code", skip_serializing_if = "Option::is_none")]
    pub subnational_region_code: Option<String>,
}

impl V1AffiliatesParlayPostRequest {
    pub fn new(event_betting_market_position_ids: Vec<i64>) -> V1AffiliatesParlayPostRequest {
        V1AffiliatesParlayPostRequest {
            country_code: None,
            event_betting_market_position_ids,
            hide_offers_links: None,
            odds_format: None,
            offer_campaign: None,
            operator_ids: None,
            operator_keys: None,
            product_mode: None,
            subnational_region_code: None,
        }
    }
}
/// Odds display format. Defaults per product_mode (dfs→multiplier, prediction_market→percent, else american).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OddsFormat {
    #[serde(rename = "american")]
    American,
    #[serde(rename = "decimal")]
    Decimal,
    #[serde(rename = "fractional")]
    Fractional,
    #[serde(rename = "multiplier")]
    Multiplier,
    #[serde(rename = "percent")]
    Percent,
}

impl Default for OddsFormat {
    fn default() -> OddsFormat {
        Self::American
    }
}
/// Display mode. dfs rewrites leg stat lines to MORE/LESS.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProductMode {
    #[serde(rename = "sportsbook")]
    Sportsbook,
    #[serde(rename = "dfs")]
    Dfs,
    #[serde(rename = "prediction_market")]
    PredictionMarket,
}

impl Default for ProductMode {
    fn default() -> ProductMode {
        Self::Sportsbook
    }
}

