/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1TrendsByBettingMarketPositionPostRequest {
    /// Array of event betting market position IDs
    #[serde(rename = "event_betting_market_position_ids")]
    pub event_betting_market_position_ids: Vec<i64>,
    /// Odds display format. Defaults per product_mode (dfs→multiplier, prediction_market→percent, else american).
    #[serde(rename = "odds_format", skip_serializing_if = "Option::is_none")]
    pub odds_format: Option<OddsFormat>,
    /// Display mode. dfs rewrites stat lines to MORE/LESS; on the paginated flows endpoints it also auto-filters to over/under player props (entity_type=player, positions [4,5]) unless an entity/position filter is set.
    #[serde(rename = "product_mode", skip_serializing_if = "Option::is_none")]
    pub product_mode: Option<ProductMode>,
    /// When true, the logo fields on each flow, leg, and multi-trend slot (default_logo_url, logo_url_1, logo_url_2) are replaced with cartoon-jersey image URLs derived from the relevant team, player, or league. When false or omitted, the original logo URLs are returned. Defaults to false.
    #[serde(rename = "use_cartoon_images", skip_serializing_if = "Option::is_none")]
    pub use_cartoon_images: Option<bool>,
}

impl V1TrendsByBettingMarketPositionPostRequest {
    pub fn new(event_betting_market_position_ids: Vec<i64>) -> V1TrendsByBettingMarketPositionPostRequest {
        V1TrendsByBettingMarketPositionPostRequest {
            event_betting_market_position_ids,
            odds_format: None,
            product_mode: None,
            use_cartoon_images: None,
        }
    }
}
/// Odds display format. Defaults per product_mode (dfs→multiplier, prediction_market→percent, else american).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OddsFormat {
    #[serde(rename = "american")]
    American,
    #[serde(rename = "decimal")]
    Decimal,
    #[serde(rename = "fractional")]
    Fractional,
    #[serde(rename = "multiplier")]
    Multiplier,
    #[serde(rename = "percent")]
    Percent,
}

impl Default for OddsFormat {
    fn default() -> OddsFormat {
        Self::American
    }
}
/// Display mode. dfs rewrites stat lines to MORE/LESS; on the paginated flows endpoints it also auto-filters to over/under player props (entity_type=player, positions [4,5]) unless an entity/position filter is set.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProductMode {
    #[serde(rename = "sportsbook")]
    Sportsbook,
    #[serde(rename = "dfs")]
    Dfs,
    #[serde(rename = "prediction_market")]
    PredictionMarket,
}

impl Default for ProductMode {
    fn default() -> ProductMode {
        Self::Sportsbook
    }
}

