/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1AffiliatesEventsPostRequest {
    #[serde(rename = "country_code")]
    pub country_code: String,
    #[serde(rename = "device_type", skip_serializing_if = "Option::is_none")]
    pub device_type: Option<DeviceType>,
    #[serde(rename = "event_type")]
    pub event_type: EventType,
    #[serde(rename = "offer_campaign", skip_serializing_if = "Option::is_none")]
    pub offer_campaign: Option<String>,
    #[serde(rename = "offer_id")]
    pub offer_id: uuid::Uuid,
    #[serde(rename = "offer_label", skip_serializing_if = "Option::is_none")]
    pub offer_label: Option<String>,
    #[serde(rename = "operator_id")]
    pub operator_id: i64,
    #[serde(rename = "session_token", skip_serializing_if = "Option::is_none")]
    pub session_token: Option<String>,
    #[serde(rename = "subnational_region_code", skip_serializing_if = "Option::is_none")]
    pub subnational_region_code: Option<String>,
}

impl V1AffiliatesEventsPostRequest {
    pub fn new(country_code: String, event_type: EventType, offer_id: uuid::Uuid, operator_id: i64) -> V1AffiliatesEventsPostRequest {
        V1AffiliatesEventsPostRequest {
            country_code,
            device_type: None,
            event_type,
            offer_campaign: None,
            offer_id,
            offer_label: None,
            operator_id,
            session_token: None,
            subnational_region_code: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeviceType {
    #[serde(rename = "ios")]
    Ios,
    #[serde(rename = "android")]
    Android,
    #[serde(rename = "desktop")]
    Desktop,
}

impl Default for DeviceType {
    fn default() -> DeviceType {
        Self::Ios
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventType {
    #[serde(rename = "impression")]
    Impression,
    #[serde(rename = "click")]
    Click,
}

impl Default for EventType {
    fn default() -> EventType {
        Self::Impression
    }
}

