/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1TrendsFlowsByIdPostRequest {
    /// Sub-type for fact flows. Defaults to 'base' if omitted.
    #[serde(rename = "fact_flow_type", skip_serializing_if = "Option::is_none")]
    pub fact_flow_type: Option<FactFlowType>,
    /// Array of flow IDs to retrieve
    #[serde(rename = "flow_ids")]
    pub flow_ids: Vec<i64>,
    #[serde(rename = "flow_type")]
    pub flow_type: FlowType,
    /// When true, the logo fields on each flow, leg, and multi-trend slot (default_logo_url, logo_url_1, logo_url_2) are replaced with cartoon-jersey image URLs derived from the relevant team, player, or league. When false or omitted, the original logo URLs are returned. Defaults to false.
    #[serde(rename = "use_cartoon_images", skip_serializing_if = "Option::is_none")]
    pub use_cartoon_images: Option<bool>,
}

impl V1TrendsFlowsByIdPostRequest {
    pub fn new(flow_ids: Vec<i64>, flow_type: FlowType) -> V1TrendsFlowsByIdPostRequest {
        V1TrendsFlowsByIdPostRequest {
            fact_flow_type: None,
            flow_ids,
            flow_type,
            use_cartoon_images: None,
        }
    }
}
/// Sub-type for fact flows. Defaults to 'base' if omitted.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FactFlowType {
    #[serde(rename = "base")]
    Base,
    #[serde(rename = "expanded")]
    Expanded,
}

impl Default for FactFlowType {
    fn default() -> FactFlowType {
        Self::Base
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FlowType {
    #[serde(rename = "fact_flow")]
    FactFlow,
    #[serde(rename = "fun_flow")]
    FunFlow,
    #[serde(rename = "fact_flow_parlay")]
    FactFlowParlay,
    #[serde(rename = "fun_flow_parlay")]
    FunFlowParlay,
    #[serde(rename = "plain_flow_parlay")]
    PlainFlowParlay,
}

impl Default for FlowType {
    fn default() -> FlowType {
        Self::FactFlow
    }
}

