/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1AccountApiKeysKeyCodeDelete409Response {
    /// Human-readable description of the constraint that blocked the operation.
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "success")]
    pub success: bool,
}

impl V1AccountApiKeysKeyCodeDelete409Response {
    pub fn new(error: String, success: bool) -> V1AccountApiKeysKeyCodeDelete409Response {
        V1AccountApiKeysKeyCodeDelete409Response {
            error,
            success,
        }
    }
}

