/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AffiliateErrorResponse {
    #[serde(rename = "error")]
    pub error: Box<models::AffiliateErrorResponseError>,
}

impl AffiliateErrorResponse {
    pub fn new(error: models::AffiliateErrorResponseError) -> AffiliateErrorResponse {
        AffiliateErrorResponse {
            error: Box::new(error),
        }
    }
}

