/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthListApiKeysResponse {
    #[serde(rename = "api_keys", skip_serializing_if = "Option::is_none")]
    pub api_keys: Option<Vec<models::AuthListApiKeysResponseApiKeysInner>>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

impl AuthListApiKeysResponse {
    pub fn new() -> AuthListApiKeysResponse {
        AuthListApiKeysResponse {
            api_keys: None,
            success: None,
        }
    }
}

