/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthSetCheckEndpointRequest {
    /// If true, the platform sends a single POST with a JSON array of all hydrated payloads. If false (default), one POST per flow is issued in parallel.
    #[serde(rename = "allow_multiple", skip_serializing_if = "Option::is_none")]
    pub allow_multiple: Option<bool>,
    /// HTTP header name used to carry the authentication credential. Defaults to 'Authorization'. Common alternatives: 'X-API-Key', 'X-Auth'.
    #[serde(rename = "auth_header_name", skip_serializing_if = "Option::is_none")]
    pub auth_header_name: Option<String>,
    /// Prefix placed before the token in the header value. Defaults to 'Bearer' when 'auth_header_name' is omitted. Set to an empty string for headers that take the raw value (e.g. 'X-API-Key').
    #[serde(rename = "auth_scheme", skip_serializing_if = "Option::is_none")]
    pub auth_scheme: Option<String>,
    /// Authentication credential. Stored server-side and never returned in any response. Sent as `<auth_header_name>: <auth_scheme> <auth_token>` (scheme omitted when empty).
    #[serde(rename = "auth_token")]
    pub auth_token: String,
    /// HTTP method used when calling the endpoint.
    #[serde(rename = "method")]
    pub method: Method,
    /// Absolute URL of the check endpoint (https recommended).
    #[serde(rename = "url")]
    pub url: String,
}

impl AuthSetCheckEndpointRequest {
    pub fn new(auth_token: String, method: Method, url: String) -> AuthSetCheckEndpointRequest {
        AuthSetCheckEndpointRequest {
            allow_multiple: None,
            auth_header_name: None,
            auth_scheme: None,
            auth_token,
            method,
            url,
        }
    }
}
/// HTTP method used when calling the endpoint.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Method {
    #[serde(rename = "POST")]
    Post,
}

impl Default for Method {
    fn default() -> Method {
        Self::Post
    }
}

