/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthListSecretsResponseSecretsInner {
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "secret_code", skip_serializing_if = "Option::is_none")]
    pub secret_code: Option<uuid::Uuid>,
    /// Masked secret preview (e.g. betflow_b2b_...5678901234)
    #[serde(rename = "secret_preview", skip_serializing_if = "Option::is_none")]
    pub secret_preview: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl AuthListSecretsResponseSecretsInner {
    pub fn new() -> AuthListSecretsResponseSecretsInner {
        AuthListSecretsResponseSecretsInner {
            created_at: None,
            secret_code: None,
            secret_preview: None,
            updated_at: None,
        }
    }
}

