/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthCreateApiKeyResponse {
    /// Plaintext API key (returned only once)
    #[serde(rename = "api_key", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    #[serde(rename = "key_code", skip_serializing_if = "Option::is_none")]
    pub key_code: Option<uuid::Uuid>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

impl AuthCreateApiKeyResponse {
    pub fn new() -> AuthCreateApiKeyResponse {
        AuthCreateApiKeyResponse {
            api_key: None,
            key_code: None,
            message: None,
            success: None,
        }
    }
}

