/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthListApiKeysResponseApiKeysInner {
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "expires_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "key_code", skip_serializing_if = "Option::is_none")]
    pub key_code: Option<uuid::Uuid>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "widget", skip_serializing_if = "Option::is_none")]
    pub widget: Option<bool>,
}

impl AuthListApiKeysResponseApiKeysInner {
    pub fn new() -> AuthListApiKeysResponseApiKeysInner {
        AuthListApiKeysResponseApiKeysInner {
            active: None,
            created_at: None,
            expires_at: None,
            key_code: None,
            name: None,
            widget: None,
        }
    }
}

