/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthOAuthLoginRequest {
    #[serde(rename = "client_id")]
    pub client_id: String,
    #[serde(rename = "client_secret")]
    pub client_secret: String,
}

impl AuthOAuthLoginRequest {
    pub fn new(client_id: String, client_secret: String) -> AuthOAuthLoginRequest {
        AuthOAuthLoginRequest {
            client_id,
            client_secret,
        }
    }
}

