/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthCreateSecretResponse {
    /// Plaintext secret (returned only once, prefixed with betflow_b2b_)
    #[serde(rename = "client_secret", skip_serializing_if = "Option::is_none")]
    pub client_secret: Option<String>,
}

impl AuthCreateSecretResponse {
    pub fn new() -> AuthCreateSecretResponse {
        AuthCreateSecretResponse {
            client_secret: None,
        }
    }
}

