/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthTokenPair {
    #[serde(rename = "access_token")]
    pub access_token: String,
    #[serde(rename = "expires_at")]
    pub expires_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "expires_in")]
    pub expires_in: i64,
    #[serde(rename = "refresh_token")]
    pub refresh_token: String,
    #[serde(rename = "token_type")]
    pub token_type: String,
}

impl AuthTokenPair {
    pub fn new(access_token: String, expires_at: chrono::DateTime<chrono::FixedOffset>, expires_in: i64, refresh_token: String, token_type: String) -> AuthTokenPair {
        AuthTokenPair {
            access_token,
            expires_at,
            expires_in,
            refresh_token,
            token_type,
        }
    }
}

