/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthCheckEndpointResponseData {
    #[serde(rename = "allow_multiple", skip_serializing_if = "Option::is_none")]
    pub allow_multiple: Option<bool>,
    #[serde(rename = "auth_header_name", skip_serializing_if = "Option::is_none")]
    pub auth_header_name: Option<String>,
    /// May be empty for raw-value header schemes like 'X-API-Key'.
    #[serde(rename = "auth_scheme", skip_serializing_if = "Option::is_none")]
    pub auth_scheme: Option<String>,
    /// Masked preview of the stored auth token (e.g. \"…aB3x\"). The full token is never returned.
    #[serde(rename = "auth_token_preview", skip_serializing_if = "Option::is_none")]
    pub auth_token_preview: Option<String>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "method", skip_serializing_if = "Option::is_none")]
    pub method: Option<Method>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl AuthCheckEndpointResponseData {
    pub fn new() -> AuthCheckEndpointResponseData {
        AuthCheckEndpointResponseData {
            allow_multiple: None,
            auth_header_name: None,
            auth_scheme: None,
            auth_token_preview: None,
            created_at: None,
            method: None,
            updated_at: None,
            url: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Method {
    #[serde(rename = "POST")]
    Post,
}

impl Default for Method {
    fn default() -> Method {
        Self::Post
    }
}

