/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthCreateApiKeyRequest {
    #[serde(rename = "name")]
    pub name: String,
}

impl AuthCreateApiKeyRequest {
    pub fn new(name: String) -> AuthCreateApiKeyRequest {
        AuthCreateApiKeyRequest {
            name,
        }
    }
}

