/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TrendsQuoteSandboxRequest : Single hydrated pricing payload — the exact shape /v1/trends/flows/quote sends in each outbound call. Wire this endpoint into /v1/account/check-endpoint to round-trip the widget call entirely on platform infrastructure (no real operator needed).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrendsQuoteSandboxRequest {
    #[serde(rename = "country")]
    pub country: String,
    /// Hydrated leg array, identical to what the quote endpoint POSTs to a real operator. Pass it through unchanged.
    #[serde(rename = "event_betting_market_position_maps")]
    pub event_betting_market_position_maps: Vec<serde_json::Value>,
    #[serde(rename = "flow_id")]
    pub flow_id: i64,
    #[serde(rename = "flow_type")]
    pub flow_type: FlowType,
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
}

impl TrendsQuoteSandboxRequest {
    /// Single hydrated pricing payload — the exact shape /v1/trends/flows/quote sends in each outbound call. Wire this endpoint into /v1/account/check-endpoint to round-trip the widget call entirely on platform infrastructure (no real operator needed).
    pub fn new(country: String, event_betting_market_position_maps: Vec<serde_json::Value>, flow_id: i64, flow_type: FlowType) -> TrendsQuoteSandboxRequest {
        TrendsQuoteSandboxRequest {
            country,
            event_betting_market_position_maps,
            flow_id,
            flow_type,
            region: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FlowType {
    #[serde(rename = "fact_flow")]
    FactFlow,
    #[serde(rename = "fun_flow")]
    FunFlow,
    #[serde(rename = "fact_flow_parlay")]
    FactFlowParlay,
    #[serde(rename = "fun_flow_parlay")]
    FunFlowParlay,
    #[serde(rename = "plain_flow_parlay")]
    PlainFlowParlay,
}

impl Default for FlowType {
    fn default() -> FlowType {
        Self::FactFlow
    }
}

