/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrendsErrorResponseError {
    /// Machine-readable error code. Possible values:   * `BAD_REQUEST` — malformed request, invalid path/query parameter, or JSON type mismatch in the body. Returned with HTTP 400.   * `VALIDATION_ERROR` — one or more request fields failed validation rules; the message names each offending field. Returned with HTTP 422 (Unprocessable Entity).   * `AMBIGUOUS_LOOKUP` — a slug identifier matched more than one record; qualify it (e.g. `country/league`) and retry.   * `UNAUTHORIZED` — missing or invalid credentials.   * `FORBIDDEN` — authenticated but not permitted to access this resource.   * `NOT_FOUND` — resource does not exist.   * `RATE_LIMIT_EXCEEDED` — too many requests.   * `INTERNAL_ERROR` — unexpected server error. 
    #[serde(rename = "code")]
    pub code: Code,
    /// Human-readable explanation of the error. For `VALIDATION_ERROR` responses, names the offending field(s) and the rule that failed.
    #[serde(rename = "message")]
    pub message: String,
}

impl TrendsErrorResponseError {
    pub fn new(code: Code, message: String) -> TrendsErrorResponseError {
        TrendsErrorResponseError {
            code,
            message,
        }
    }
}
/// Machine-readable error code. Possible values:   * `BAD_REQUEST` — malformed request, invalid path/query parameter, or JSON type mismatch in the body. Returned with HTTP 400.   * `VALIDATION_ERROR` — one or more request fields failed validation rules; the message names each offending field. Returned with HTTP 422 (Unprocessable Entity).   * `AMBIGUOUS_LOOKUP` — a slug identifier matched more than one record; qualify it (e.g. `country/league`) and retry.   * `UNAUTHORIZED` — missing or invalid credentials.   * `FORBIDDEN` — authenticated but not permitted to access this resource.   * `NOT_FOUND` — resource does not exist.   * `RATE_LIMIT_EXCEEDED` — too many requests.   * `INTERNAL_ERROR` — unexpected server error. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "BAD_REQUEST")]
    BadRequest,
    #[serde(rename = "VALIDATION_ERROR")]
    ValidationError,
    #[serde(rename = "AMBIGUOUS_LOOKUP")]
    AmbiguousLookup,
    #[serde(rename = "UNAUTHORIZED")]
    Unauthorized,
    #[serde(rename = "FORBIDDEN")]
    Forbidden,
    #[serde(rename = "NOT_FOUND")]
    NotFound,
    #[serde(rename = "RATE_LIMIT_EXCEEDED")]
    RateLimitExceeded,
    #[serde(rename = "INTERNAL_ERROR")]
    InternalError,
}

impl Default for Code {
    fn default() -> Code {
        Self::BadRequest
    }
}

