/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrendsQuoteFlowItem {
    /// ISO 3166-1 alpha-2 country code (e.g. 'US', 'IT'). Uppercased server-side.
    #[serde(rename = "country")]
    pub country: String,
    /// Leg identifiers that make up this flow. Length 1 = single, length 2+ = parlay.
    #[serde(rename = "event_betting_market_position_ids")]
    pub event_betting_market_position_ids: Vec<i64>,
    #[serde(rename = "flow_id")]
    pub flow_id: i64,
    #[serde(rename = "flow_type")]
    pub flow_type: FlowType,
    /// Sub-national region code (e.g. 'NJ', 'WA'). Uppercased server-side.
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
}

impl TrendsQuoteFlowItem {
    pub fn new(country: String, event_betting_market_position_ids: Vec<i64>, flow_id: i64, flow_type: FlowType) -> TrendsQuoteFlowItem {
        TrendsQuoteFlowItem {
            country,
            event_betting_market_position_ids,
            flow_id,
            flow_type,
            region: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FlowType {
    #[serde(rename = "fact_flow")]
    FactFlow,
    #[serde(rename = "fun_flow")]
    FunFlow,
    #[serde(rename = "fact_flow_parlay")]
    FactFlowParlay,
    #[serde(rename = "fun_flow_parlay")]
    FunFlowParlay,
    #[serde(rename = "plain_flow_parlay")]
    PlainFlowParlay,
}

impl Default for FlowType {
    fn default() -> FlowType {
        Self::FactFlow
    }
}

