/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TrendsQuoteSandboxResponse : Mock pricing response. Shape differs between single (1-leg) and parlay (2+ legs); parlay responses additionally carry top-level combined odds and is_combinable / parlay_failure_reason.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrendsQuoteSandboxResponse {
    /// Parlay only. Null when uncombinable.
    #[serde(rename = "american_odds_value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub american_odds_value: Option<Option<String>>,
    /// Synthetic bet-slip identifier (prefix 'FD-MOCK-'). Null when the result is invalid or the parlay is uncombinable.
    #[serde(rename = "button_payload", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub button_payload: Option<Option<String>>,
    #[serde(rename = "decimal_odds_value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub decimal_odds_value: Option<Option<f64>>,
    #[serde(rename = "event_betting_market_position_maps")]
    pub event_betting_market_position_maps: Vec<serde_json::Value>,
    #[serde(rename = "flow_id")]
    pub flow_id: i64,
    #[serde(rename = "flow_type")]
    pub flow_type: String,
    #[serde(rename = "fractional_odds_value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fractional_odds_value: Option<Option<String>>,
    /// Parlay only. False if any leg failed or the parlay-level uncombinable roll fired.
    #[serde(rename = "is_combinable", skip_serializing_if = "Option::is_none")]
    pub is_combinable: Option<bool>,
    #[serde(rename = "odds_implied_probability", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub odds_implied_probability: Option<Option<f64>>,
    #[serde(rename = "parlay_failure_reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parlay_failure_reason: Option<Option<ParlayFailureReason>>,
    #[serde(rename = "payout_multiplier", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payout_multiplier: Option<Option<f64>>,
}

impl TrendsQuoteSandboxResponse {
    /// Mock pricing response. Shape differs between single (1-leg) and parlay (2+ legs); parlay responses additionally carry top-level combined odds and is_combinable / parlay_failure_reason.
    pub fn new(event_betting_market_position_maps: Vec<serde_json::Value>, flow_id: i64, flow_type: String) -> TrendsQuoteSandboxResponse {
        TrendsQuoteSandboxResponse {
            american_odds_value: None,
            button_payload: None,
            decimal_odds_value: None,
            event_betting_market_position_maps,
            flow_id,
            flow_type,
            fractional_odds_value: None,
            is_combinable: None,
            odds_implied_probability: None,
            parlay_failure_reason: None,
            payout_multiplier: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ParlayFailureReason {
    #[serde(rename = "one or more legs failed")]
    OneOrMoreLegsFailed,
    #[serde(rename = "selections are not combinable")]
    SelectionsAreNotCombinable,
}

impl Default for ParlayFailureReason {
    fn default() -> ParlayFailureReason {
        Self::OneOrMoreLegsFailed
    }
}

