/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrendsWidgetEventRequest {
    /// Arbitrary JSON object carrying event-specific fields. May be an empty object.
    #[serde(rename = "event_body")]
    pub event_body: std::collections::HashMap<String, serde_json::Value>,
    /// The kind of client-side widget interaction being reported.
    #[serde(rename = "event_type")]
    pub event_type: EventType,
    /// Optional widget mode the interaction occurred in. Defaults to `clean`.
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Mode>,
}

impl TrendsWidgetEventRequest {
    pub fn new(event_body: std::collections::HashMap<String, serde_json::Value>, event_type: EventType) -> TrendsWidgetEventRequest {
        TrendsWidgetEventRequest {
            event_body,
            event_type,
            mode: None,
        }
    }
}
/// The kind of client-side widget interaction being reported.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventType {
    #[serde(rename = "impression")]
    Impression,
    #[serde(rename = "click")]
    Click,
    #[serde(rename = "dwell")]
    Dwell,
    #[serde(rename = "cart_open")]
    CartOpen,
    #[serde(rename = "cart_offers_shown")]
    CartOffersShown,
    #[serde(rename = "cart_dismiss")]
    CartDismiss,
    #[serde(rename = "card_click")]
    CardClick,
    #[serde(rename = "graph_expand")]
    GraphExpand,
    #[serde(rename = "graph_metric_change")]
    GraphMetricChange,
    #[serde(rename = "filter_change")]
    FilterChange,
    #[serde(rename = "widget-impression")]
    WidgetImpression,
    #[serde(rename = "widget-viewed")]
    WidgetViewed,
    #[serde(rename = "betslip-clicked")]
    BetslipClicked,
    #[serde(rename = "betslip-shared")]
    BetslipShared,
    #[serde(rename = "flow-clicked")]
    FlowClicked,
    #[serde(rename = "flow-shared")]
    FlowShared,
}

impl Default for EventType {
    fn default() -> EventType {
        Self::Impression
    }
}
/// Optional widget mode the interaction occurred in. Defaults to `clean`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "operator")]
    Operator,
    #[serde(rename = "affiliate")]
    Affiliate,
    #[serde(rename = "clean")]
    Clean,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Operator
    }
}

