/*
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrendsWidgetEventResponse {
    #[serde(rename = "status")]
    pub status: Status,
}

impl TrendsWidgetEventResponse {
    pub fn new(status: Status) -> TrendsWidgetEventResponse {
        TrendsWidgetEventResponse {
            status,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "accepted")]
    Accepted,
}

impl Default for Status {
    fn default() -> Status {
        Self::Accepted
    }
}

